GET http://localhost:8000/listusers

###
GET  http://localhost:8000/listimobi

###
GET  http://localhost:8000/session

###
POST http://localhost:8000/creatusers
Content-Type: application/json

{
    "name": "Amado Batista",
    "email": "amado@batista.com",
    "password": "brega"
}







###router.post('/creatusers'
### get('/listusers
### get('/listusers/:userId'
### post('/session'
### post('/createimobi', upload.single("thumb"), ImobiController.craeteImobi);
### get('/listimobi'
### get('/listimobi/:slug', 
### post('/createmessage', 
### get('/listmessage/:id',,
